#    os: [ubuntu-latest, windows-2019 , macos-latest]
#        container: ['']
#        include:
#          - os: ubuntu-latest
#            container: centos:centos7

name: build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v2
    - uses: "actions/setup-python@v2"
      with:
        python-version: 3.6   
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip numpy
        
    - if: matrix.container == 'centos:centos7'
      name: Install prerequisites for Docker CentOS7
      shell: bash
      run: |
        yum -y install epel-release
        yum group install -y "Development Tools"
        yum install -y cmake3 git subversion
        ln -s /usr/bin/cmake3 /usr/bin/cmake
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
    
    - if: matrix.os == 'ubuntu-latest'
      name: Configure CMake for Ubuntu
      shell: bash
      run: |
        sudo apt-get install -y cucumber
        sudo apt-get install -y ruby-rspec
        cmake -E make_directory "${{runner.workspace}}/build"
        cd "${{runner.workspace}}/build"
        echo Configuring in $(pwd)
        cmake "${{github.workspace}}" -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        
    - if: matrix.os == 'macos-latest'
      name: Configure CMake for  MacoS
      shell: bash
      run: |
        brew install cucumber-ruby
        cmake -E make_directory "${{runner.workspace}}/build"
        cd "${{runner.workspace}}/build"
        echo Configuring in $(pwd)
        cmake "${{github.workspace}}" -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - if: matrix.os == 'windows-2019'
      name: Configure CMake for Windows
      shell: bash
      run: |
        cmake -E make_directory "${{runner.workspace}}/build"
        cd "${{runner.workspace}}/build"
        echo Configuring in $(pwd)
        cmake "${{github.workspace}}" -G "Visual Studio 16 2019" -A x64 -DINCLUDE_VENDOR_LIBRARIES=NO   
        
    - name: Build on all platforms
      shell: bash
      run: |
        cd "${{runner.workspace}}/build"
        echo Building in $(pwd)
        cmake --build . --config $BUILD_TYPE 

    - if: matrix.os == 'ubuntu-latest'
      name: Test
      shell: bash
      run: |
        cd ${{runner.workspace}}/build/test
        rm -rf smoke-tests
        cp -r ${{github.workspace}}/test/smoke-tests/ .
        cd smoke-tests
        cucumber
